# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae5c4939824c02f9a1b4b68d890589dbc475f77e4876a4bdcd4bd19e1c4395261a29b2a5208cc0d61efa56cef130e106893d7ec8980a5ad30b3c9717a6b5af25

test:
  secret_key_base: a33007713f06553b241dea61140f433116765d7de532955a0038441f1d68df6e44214247676e43670a608ca17f3b3554e9985d0df3d99b1cc0d50ec4d977e0f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
